import type { Quote, OHLCV } from '../types.js';
import type { Result } from '../result.js';
import { ok, err } from '../result.js';
import { ProviderError } from '../errors.js';
import type { IMarketDataProvider } from './interface.js';

/**
 * Deterministic in-memory provider for local development, testing, and
 * Jetro canvas rendering when a live data feed is unavailable.
 *
 * Price series are generated by a seeded LCG so they remain stable
 * across runs for the same ticker, enabling reproducible UI snapshots.
 */
export class MockProvider implements IMarketDataProvider {
  readonly name = 'mock';

  // Base prices per ticker; unknown tickers get a fallback of 1000.
  private static readonly BASE_PRICES: Record<string, number> = {
    'TCS.NS': 3980, 'INFY.NS': 1595, 'HCLTECH.NS': 1512, 'WIPRO.NS': 532,
    'PERSISTENT.NS': 5640, 'LTIM.NS': 5780,
    'RELIANCE.BO': 2920, 'HDFCBANK.BO': 1845, 'HINDUNILVR.BO': 2680,
    'ITC.BO': 488, 'NESTLEIND.BO': 25600, 'TATAMOTORS.BO': 892,
    'ZOMATO.NS': 228, 'IRCTC.NS': 862, 'TATAELXSI.NS': 7860,
    'DIXON.NS': 10200, 'POLYCAB.NS': 6420,
  };

  async fetchQuote(ticker: string): Promise<Result<Quote>> {
    const base = MockProvider.BASE_PRICES[ticker] ?? 1000;
    const jitter = this.seededNoise(ticker, 0) * 0.02;
    const price = parseFloat((base * (1 + jitter)).toFixed(2));
    const prevClose = parseFloat((base * (1 - this.seededNoise(ticker, 1) * 0.01)).toFixed(2));

    return ok({
      ticker,
      price,
      open: parseFloat((price * 0.998).toFixed(2)),
      high: parseFloat((price * 1.01).toFixed(2)),
      low: parseFloat((price * 0.99).toFixed(2)),
      previousClose: prevClose,
      change: parseFloat((price - prevClose).toFixed(2)),
      changePct: parseFloat((((price - prevClose) / prevClose) * 100).toFixed(2)),
      volume: Math.floor(100000 + this.seededNoise(ticker, 2) * 500000),
      fetchedAt: new Date().toISOString(),
    });
  }

  async fetchHistory(ticker: string, days: number): Promise<Result<OHLCV[]>> {
    const base = MockProvider.BASE_PRICES[ticker] ?? 1000;
    const series = this.generatePriceSeries(ticker, base, days);
    const today = new Date();

    const ohlcv: OHLCV[] = series.map((close, i) => {
      const d = new Date(today);
      d.setDate(d.getDate() - (days - 1 - i));
      const open = parseFloat((close * (1 - 0.005)).toFixed(2));
      return {
        date: d.toISOString().slice(0, 10),
        open,
        high: parseFloat((close * 1.01).toFixed(2)),
        low: parseFloat((close * 0.99).toFixed(2)),
        close,
        volume: Math.floor(80000 + this.seededNoise(`${ticker}${i}`, 0) * 400000),
      };
    });

    return ok(ohlcv);
  }

  async fetchBulkQuotes(tickers: string[]): Promise<Result<Map<string, Quote>>> {
    const map = new Map<string, Quote>();
    for (const ticker of tickers) {
      const result = await this.fetchQuote(ticker);
      if (!result.ok) return err(new ProviderError(result.error.message, this.name));
      map.set(ticker, result.value);
    }
    return ok(map);
  }

  async isAvailable(): Promise<boolean> {
    return true;
  }

  // ── Internals ───────────────────────────────────────────────────────────────

  private seededNoise(seed: string, offset: number): number {
    let h = offset * 2654435761;
    for (let i = 0; i < seed.length; i++) {
      h = Math.imul(h ^ seed.charCodeAt(i), 2654435761);
    }
    return ((h >>> 0) / 0xffffffff) * 2 - 1;
  }

  private generatePriceSeries(ticker: string, ltp: number, days: number): number[] {
    const prices: number[] = [ltp];
    for (let i = 1; i < days; i++) {
      const noise = this.seededNoise(`${ticker}_d${i}`, 0);
      const prev = prices[prices.length - 1]!;
      prices.push(parseFloat((prev * (1 + noise * 0.018)).toFixed(2)));
    }
    // Walk backward so the last element is always `ltp`.
    return prices.reverse();
  }
}
